core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tasks.urls')),
    path('users/', include('users.urls')),

]

tasks/urls.py
from django.urls import path
from . import views


app_name = 'tasks'

urlpatterns = [
    path('', views.HomeView, name='home'),
    path('create/', views.createTask, name='create'),
    path('task/<int:id>', views.updateTask, name='detail'),

]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupView, name='signup'),
    path('signin/', views.signinView, name='signin'),
    path('signout/', views.signoutView, name='signout'),


]

tasks/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Task(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    description = models.TextField()
    completed = models.BooleanField(default=False)

    def __str__(self):
        return self.title

users/models.py
from django.db import models

# Create your models here.

tasks/forms.py
from django.forms import ModelForm
from .models import Task


class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description']

tasks/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Task
from .forms import TaskForm

# Create your views here.


def HomeView(request):

    if request.user.is_authenticated:
        tasks = Task.objects.filter(owner=request.user)

        context = {
            'tasks': tasks
        }

    else:
        context = {}

    return render(request, 'tasks/home.html', context)


def createTask(request):

    context = {
        'form': TaskForm
    }

    if request.method == 'GET':
        return render(request, 'tasks/create.html', context)

    else:
        try:
            form = TaskForm(request.POST)
            if form.is_valid():
                new_task = form.save(commit=False)
                new_task.owner = request.user
                new_task.save()
            else:
                context['form'] = form
                return render(request, 'tasks/create.html', context)
        except Exception as e:
            context['message'] = e
            return render(request, 'tasks/create.html', context)

        return redirect('tasks:home')


def updateTask(request, id):
    context = {}
    try:
        task = get_object_or_404(Task, id=id, owner=request.user)
    except Exception as e:
        return redirect('tasks:home')

    form = TaskForm(instance=task)
    context['form'] = form

    if request.method == 'GET':

        return render(request, 'tasks/update.html', context)

    else:
        try:
            new_task = TaskForm(request.POST, instance=task)
            new_task.save()

            return redirect('tasks:home')

        except Exception as e:
            context['message'] = e
            return render(request, 'tasks/update.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.db import IntegrityError


# Create your views here.


def signupView(request):

    context = {
        'form': UserCreationForm
    }

    if request.method == 'GET':

        return render(request, 'users/signup.html', context)

    else:

        if request.POST['password1'] == request.POST['password2']:
            try:
                user = User.objects.create_user(
                    username=request.POST['username'],
                    password=request.POST['password1']
                )

                user.save()
                login(request, user)

                return redirect('tasks:index')
            except IntegrityError:
                context['message'] = 'Username already exists'
                return render(request, 'users/signup.html', context)
            except Exception as e:
                context['message'] = 'Something went wrong, please contact the administrator'
                return render(request, 'users/signup.html', context)

        context['message'] = 'Error password do not match'
        return render(request, 'users/signup.html', context)


def signinView(request):

    context = {
        'form': AuthenticationForm
    }

    if request.method == 'GET':

        return render(request, 'users/signin.html', context)

    else:
        user = authenticate(
            username=request.POST['username'],
            password=request.POST['password']
        )

        if user is not None:
            login(request, user)
            return redirect('tasks:home')
        else:
            context['message'] = 'Invalid username or password'
            return render(request, 'users/signin.html', context)


def signoutView(request):

    logout(request)

    return redirect('tasks:home')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tasks Crud</title>

    {% comment %} BOOTSTRAP{% endcomment %}

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    {% include 'includes/navbar.html' %}

    <div class="container my-5">

        {% block content %}
    
        {% endblock  %}
    </div>


    {% comment %} BOOTSTRAP {% endcomment %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    
</body>
</html>

templates/includes/navbar.html
<nav class="navbar navbar-expand navbar-dark bg-dark">
    <div class="nav navbar-nav">
        <a class="nav-item nav-link active" href="{% url "tasks:home" %}" aria-current="page"
            >TasksAPP <span class="visually-hidden">(current)</span></a
        >
        <a class="nav-item nav-link" href="{% url "tasks:home" %}">Home</a>

        {% if user.is_authenticated %}
            <a class="nav-item nav-link" href="{% url "users:signout" %}">Logout</a>
        {% else %}
            <a class="nav-item nav-link" href="{% url "users:signin" %}">Login</a>
            <a class="nav-item nav-link" href="{% url "users:signup" %}">Signup</a>
        {% endif %}


    </div>
</nav>

templates/tasks/create.html
{% extends "../base.html" %}


{% block content %}


    {% if message %}

        {{message}}
    
    {% endif %}

    <div class="card">

        <form method="post">

            {% csrf_token %}

            {{form.as_p}}


            <button>Create Task</button>
        </form>

    </div>

{% endblock  %}

templates/tasks/home.html
{% extends '../base.html' %}


{% block content %}

    <h1>Welcome to the tasks crud</h1>


    {% if user.is_authenticated %}

        {% if message %}

            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
        
        {% endif %}

        <p>You are logged in as {{ user.username }}</p>

        <a class="btn btn-primary" href="{% url 'tasks:create' %}">Create a Task</a>

        {% for task in tasks %}

            <div class="row">
                <div class="col-md-12">
                    <div class="card m-2 ">
                        <div class="card-body">
                            <h2 class="card-title">{{task.title}}</h2>
                            <p class="card-text">{{task.description}}</p>

                            <a class="btn btn-primary" href="{% url 'tasks:detail' task.id %}">Detail</a>
                        </div>
                    </div>
                </div>
            </div>
    
        {% endfor %}

    {% else %}

        <p>
            Do you have an account? sining here <a href="{% url "users:signin" %}">here </a>or <a href="{% url "users:signup" %}">create one</a>
        </p>
    
    {% endif %}
    
    

{% endblock  %}

templates/tasks/update.html
{% extends "../base.html" %}


{% block content %}


    {% if message %}

        {{message}}
    
    {% endif %}

    <div class="card">

        <form method="post">

            {% csrf_token %}

            {{form.as_p}}


            <button>Update Task</button>
        </form>

    </div>

{% endblock  %}

templates/users/signin.html
{% extends '../base.html' %}


{% block content %}

    <h2>signin</h2>


    <form method='post'>

        {% csrf_token %}

        {{ form.as_p }}


        <button>Signin</button>

    </form>


{% endblock  %}

templates/users/signup.html
{% extends '../base.html' %}


{% block content %}

    <h1>Signup</h1>

    <form method="post" >

        {% if message %}
            <p>{{message}}</p>
        {% endif %}

        {% csrf_token %}

        {{form.as_p}}

        <button>Signup</button>

    </form>

{% endblock  %}